# Generated by Django 4.0.1 on 2022-03-20 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_userr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userr',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userr',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
